# Generated by Django 4.1.2 on 2023-08-28 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_id', models.IntegerField(blank=True, null=True, verbose_name='Register')),
                ('pieces', models.IntegerField(default=1)),
                ('gross_weight', models.DecimalField(decimal_places=3, max_digits=16, verbose_name='Gross Wt.')),
                ('studs_weight', models.DecimalField(decimal_places=3, max_digits=16, verbose_name='Studs Wt.')),
                ('less_weight', models.DecimalField(decimal_places=3, max_digits=16, verbose_name='Less Wt.')),
                ('net_weight', models.DecimalField(decimal_places=3, max_digits=16, verbose_name='Net Wt.')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=16)),
                ('calculation', models.CharField(choices=[('Making Charges', 'Making Charges'), ('Wastage', 'Wastage'), ('MRP', 'MRP')], default='Making Charges', max_length=32)),
                ('making_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Making')),
                ('wastage', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='MRP')),
                ('description', models.TextField(blank=True)),
                ('purchase_date', models.DateField(blank=True, verbose_name='Date')),
                ('lot_number', models.IntegerField(blank=True, null=True, verbose_name='Lot Number')),
                ('design_code', models.CharField(blank=True, max_length=32, verbose_name='Design Code')),
                ('old_id', models.CharField(blank=True, max_length=16, verbose_name='Jilaba ID')),
                ('sold', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='masters.category')),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='masters.metal')),
                ('purity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='masters.purity')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='masters.type')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('firm', models.CharField(blank=True, max_length=64)),
                ('contact', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('old_id', models.CharField(blank=True, max_length=16)),
                ('old_description', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('less', models.BooleanField(default=False)),
                ('colour', models.CharField(blank=True, max_length=64)),
                ('shape', models.CharField(blank=True, max_length=64)),
                ('quantity', models.IntegerField(default=1)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=16)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=16)),
                ('value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studs', to='stock.product')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studs', to='masters.stud_type')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studs', to='masters.unit')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stock.vendor'),
        ),
    ]
