# Generated by Django 4.0.5 on 2022-06-30 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.IntegerField(blank=True)),
                ('pieces', models.IntegerField(default=1)),
                ('gross_weight', models.DecimalField(decimal_places=3, max_digits=16)),
                ('studs_weight', models.DecimalField(decimal_places=3, max_digits=16)),
                ('less_weight', models.DecimalField(decimal_places=3, max_digits=16)),
                ('net_weight', models.DecimalField(decimal_places=3, max_digits=16)),
                ('calculation', models.CharField(choices=[('Making_Charges', 'Making_Charges'), ('Wastage', 'Wastage'), ('MRP', 'MRP')], max_length=32)),
                ('making_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=16)),
                ('wastage', models.DecimalField(blank=True, decimal_places=2, max_digits=16)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=16)),
                ('description', models.TextField(blank=True)),
                ('purchase_date', models.DateField(blank=True)),
                ('lot_number', models.IntegerField(blank=True, null=True)),
                ('design_code', models.CharField(blank=True, max_length=32)),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('sold', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='masters.category')),
                ('home_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sales.home_sale')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sales.invoice')),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='masters.metal')),
                ('purity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='masters.purity')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='masters.type')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('firm', models.CharField(blank=True, max_length=64)),
                ('contact', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('old_id', models.IntegerField(blank=True)),
                ('old_description', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('less', models.BooleanField(default=False)),
                ('colour', models.CharField(blank=True, max_length=64)),
                ('shape', models.CharField(blank=True, max_length=64)),
                ('quantity', models.IntegerField(default=1)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=16)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=16)),
                ('value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studs', to='stock.product')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studs', to='masters.stud_type')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studs', to='masters.unit')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stock.vendor'),
        ),
    ]
