# Generated by Django 4.0.5 on 2022-06-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('firm', models.CharField(blank=True, max_length=64)),
                ('pan', models.CharField(blank=True, max_length=64)),
                ('gst', models.CharField(blank=True, max_length=64)),
                ('contact', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('pincode', models.CharField(blank=True, max_length=16)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('IMPS', 'IMPS'), ('UPI', 'UPI')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=64)),
                ('card_bank', models.CharField(blank=True, max_length=64)),
                ('card_number', models.CharField(blank=True, max_length=64)),
                ('cheque_number', models.CharField(blank=True, max_length=64)),
                ('cheque_branch', models.CharField(blank=True, max_length=64)),
                ('cheque_account_number', models.CharField(blank=True, max_length=64)),
                ('cheque_ifsc', models.CharField(blank=True, max_length=64)),
                ('upi_vpa', models.CharField(blank=True, max_length=64)),
                ('upi_mobile', models.CharField(blank=True, max_length=64)),
                ('wire_account_number', models.CharField(blank=True, max_length=64)),
                ('wire_utr', models.CharField(blank=True, max_length=64)),
                ('wire_bank', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
