# Generated by Django 4.0.5 on 2022-06-28 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='masters.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Advance_Payment',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='masters.payment')),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.advance')),
            ],
            bases=('masters.payment',),
        ),
    ]
