# Generated by Django 4.1.2 on 2023-06-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='untagged',
            name='pieces',
            field=models.IntegerField(default=1),
        ),
    ]
